### ISSUE TITLE
Chests stop functioning with ActuallyFaster enabled

### ISSUE THREAD

**Issue by corang** [FelixVolo/ActuallyFaster#14]
Profile export is attached. Chests cannot be opened when mod is active, when ActuallyFaster is disabled chests function again
[profile-export.zip](https://github.com/user-attachments/files/17082390/profile-export.zip)

**Comment by kgDraco** [comment]
I also had this.

the issue occurs if all of these flags are set to false:

-Chance Shrine brrrrrt=false
-Cauldron brrrrrt=false
-Cleansing Pool brrrrrt=false

Only occurs if BepInExPack is enabled; tested with & without other mods. Does not seem to matter if the other flags are true or false.

**Comment by FelixVolo** [comment]
Thanks for answering @kgDraco kgDraco :)

I'll take a deep look in it on monday

**Comment by FelixVolo** [comment]
Didn't even need a deep look. My bad. 😶‍🌫️ 

`if (chanceShrine.Value || cauldron.Value || cleansingPool.Value)
            {
                orig(self, activator);`
                
orig() was only called after the config check not before. That's why this mod messes up every PurchaseInteraction when every flag is set to false. I'll change the order of it and this should do the trick :)

**Comment by FelixVolo** [comment]
Just tested it and uploaded the update. Sorry for the inconvenience. Let's hope it works for you as well now. Thank you @kgDraco for your previous issue and your new found hint. It made things a lot easier :)
